# Generated by Django 6.0.1 on 2026-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_conversation_is_group_conversation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_disabled_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_removed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
    ]
