# Generated by Django 6.0.1 on 2026-06-05 10:18

import apps.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_conversation_is_disabled_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.storage_paths.communication_upload_path),
        ),
    ]
