# Generated by Django 6.0.5 on 2026-06-08 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_expand_ai_file_extensions'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'),
        ),
    ]
