# Generated by Django 6.0.1 on 2026-05-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0001_initial'),
        ('resources', '0003_vaultresource_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudydocument',
            name='source_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_documents', to='resources.vaultresource'),
        ),
    ]
