# Generated by Django 6.0.1 on 2026-05-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0002_aistudydocument_source_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudydocument',
            name='quiz_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
