# Generated by Django 6.0.1 on 2026-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0003_aistudydocument_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudydocument',
            name='flashcards_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='quiz_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='summary_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
