# Generated by Django 6.0.1 on 2026-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_lab', '0004_aistudydocument_flashcards_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudydocument',
            name='ai_processing_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='model_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='aistudydocument',
            name='request_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
