# Generated by Django 6.0.1 on 2026-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(default='en', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='profile_visibility',
            field=models.CharField(choices=[('friends', 'Friends only'), ('campus', 'Same university'), ('private', 'Private')], default='friends', max_length=16),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reduce_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='timezone',
            field=models.CharField(default='Asia/Dhaka', max_length=64),
        ),
    ]
