# Generated by Django 6.0.1 on 2026-06-05 10:18

import apps.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_promote_superusers_to_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=apps.storage_paths.profile_picture_upload_path),
        ),
    ]
