# Generated by Django 6.0.1 on 2026-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_user_unique_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='routine_time_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
