# Generated by Django 6.0.1 on 2026-05-31 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reminder', 'Reminder'), ('task', 'Task'), ('file', 'File'), ('ai', 'AI'), ('message', 'Message')], default='info', max_length=16)),
                ('page', models.CharField(blank=True, max_length=40)),
                ('url', models.URLField(blank=True)),
                ('course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=120)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('owner', 'source_key'), name='unique_notification_source_per_user')],
            },
        ),
    ]
