# Generated by Django 6.0.5 on 2026-06-08 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', '-created_at'], name='notif_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', 'source_key'], name='notif_owner_source_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', 'is_read'], name='notif_owner_read_idx'),
        ),
    ]
