# Generated by Django 6.0.1 on 2026-06-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_studysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accumulated_study_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='study_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
