# Generated by Django 6.0.5 on 2026-06-08 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_accumulated_study_minutes_task_study_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'due_at', 'status'], name='task_user_due_status_idx'),
        ),
    ]
