# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.PositiveSmallIntegerField(choices=[(0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")])),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("course_code", models.CharField(max_length=40)),
                ("course_title", models.CharField(max_length=160)),
                ("room_number", models.CharField(max_length=80)),
                ("faculty_initial", models.CharField(blank=True, max_length=20)),
                ("color", models.CharField(choices=[("blue", "Blue"), ("purple", "Purple"), ("green", "Green"), ("orange", "Orange")], default="blue", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routine_slots", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["day", "start_time", "course_code"],
            },
        ),
    ]
