# Generated by Django 6.0.5 on 2026-06-08 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='routineslot',
            index=models.Index(fields=['user', 'day', 'start_time'], name='routine_user_day_start_idx'),
        ),
    ]
