# Generated by Codex on 2026-05-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("semester", models.PositiveSmallIntegerField()),
                ("code", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vault_courses", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-semester", "code"],
                "unique_together": {("user", "semester", "code")},
            },
        ),
        migrations.CreateModel(
            name="VaultResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("mid_term", "Mid Term"), ("final", "Final"), ("assignment", "Assignment / Presentation"), ("link", "Links")], max_length=24)),
                ("title", models.CharField(max_length=180)),
                ("resource_type", models.CharField(choices=[("pdf", "PDF"), ("doc", "Document"), ("slide", "Slide"), ("image", "Image"), ("link", "Link"), ("other", "Other")], default="pdf", max_length=16)),
                ("url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resources", to="resources.vaultcourse")),
            ],
            options={
                "ordering": ["category", "-created_at"],
            },
        ),
    ]
