# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultresource",
            name="file",
            field=models.FileField(blank=True, upload_to="vault_resources/"),
        ),
    ]
