# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_vaultresource_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaultresource",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaultresource",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
