# Generated by Django 6.0.1 on 2026-06-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_vaultresource_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultresource',
            name='content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='is_removed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='vaultresource',
            name='public_access_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
