# Generated by Django 6.0.1 on 2026-06-05 10:18

import apps.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_vaultresource_content_type_vaultresource_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultresource',
            name='file',
            field=models.FileField(blank=True, upload_to=apps.storage_paths.vault_resource_upload_path),
        ),
    ]
